--- #YAML:1.0
name:                Test-Pod
version:             1.24
abstract:            ~
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              ~
distribution_type:   module
requires:     
    File::Spec:                    0
    Pod::Simple:                   2.04
    Test::Builder::Tester:         1.02
    Test::More:                    0.62
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
